### ISSUE TITLE
Setup demo data in qwc-demo-db

### ISSUE THREAD

**Issue by benoitblanc** [qwc-services/qwc-base-db#2]
Hi,

I would like to know if there are some reasons to setup demo data in [qwc-base-db](https://github.com/qwc-services/qwc-base-db) docker image instead of [qwc-demo-db](https://github.com/qwc-services/qwc-demo-db) image ?

`qwc-base-db` should initialize database and run migrations with alembic and `qwc-demo-db` should do the same (based on `qwc-base-db`) and add data from [`setup-demo-data.sh`](https://github.com/qwc-services/qwc-base-db/blob/d18352aacd95f1fa4b6d3f6f84ccb59172d75478/setup-demo-data.sh).

What do you think about it @manisandro @pka ?

Thanks

**Comment by manisandro** [comment]
@tpo Can you answer this?

**Comment by manisandro** [comment]
I've moved the demo setup to qwc-demo-db.

**Comment by benoitblanc** [comment]
Thanks @manisandro :smiley:
