### ISSUE TITLE
README.md: Persistent storage

### ISSUE THREAD

**Issue by loyeyoung** [qwc-services/qwc-base-db#6]
README.md states:
> For persistent storage, mount folder volume to `/var/lib/postgresql/docker`

1.  Being new to docker internals, I do not understand the nomenclature "mount folder volume to [directory]". How to "mount folder volume"?

2.  It seems that the first step would be to create the directory. In bash:
```
NEW_DIR="/var/lib/postgresql/docker"
if [ ! -d "$NEW_DIR" ] ; then
    if ! mkdir -p "$NEW_DIR" ; then
        echo "ERROR: Directory create failed."
    else
        echo "INFO: Directory created: $NEW_DIR"
    fi
else
    echo "ERROR: Directory $NEW_DIR already exists. Doing nothing."
fi
```

3. Is the path correct? Various distributions locate the path to the PostgreSQL data files differently. Note that if PostgreSQL is running, the -D command line flag tells us where the data directory is, so `ps aux | grep pgsql` reveals the data directory:
```
[root@localhost ~]# ps aux | grep pgsql
postgres    1284  0.0  0.3 215060 28672 ?        Ss    2023   3:33 /usr/pgsql-15/bin/postmaster -D **/var/lib/pgsql/15/data/**
```

**Comment by HusseinKabbout** [comment]
`/var/lib/postgresql/docker` refers to the path in the docker container. If you take a look at this [example](https://github.com/qwc-services/qwc-docker/blob/ca0875a5f14b66ea4542d1286b6b8398e9506a79/docker-compose-example.yml#L22) then you can see that we use the host path `./volumes/db` and mount it to`/var/lib/postgresql/docker` in the docker container.

Does this help you with your problem?

If you are new to docker, then I would read https://docs.docker.com/storage/volumes/ to understand more how these volumes work.

**Comment by loyeyoung** [comment]
> For persistent storage, mount folder volume to /var/lib/postgresql/docker

> we use the host path `./volumes/db` and mount it to`/var/lib/postgresql/docker` in the docker container.

So do I understand correctly that the docker is _already_ configured for persistent storage? If so, the README.md should be so clarified. Suggested lingo:

> Persistent storage is configured [by default](https://github.com/qwc-services/qwc-docker/blob/ca0875a5f14b66ea4542d1286b6b8398e9506a79/docker-compose-example.yml#L22) because the host path `./volumes/db` is mounted to`/var/lib/postgresql/docker` in the docker container.

**Comment by manisandro** [comment]
This repo here does not ship any configuration, that is done in `qwc-docker` resp. its `docker-compose.yml`. The README here explains the available configuration options, `qwc-docker` provides a sample configuration based on these options. So it would be incorrect to state in this README that a volume is mounted by default.

**Comment by loyeyoung** [comment]
@manisandro 
Your point is well taken. The better place to document would be in [qwc-services.github.io](https://github.com/qwc-services/qwc-services.github.io) and perhaps in the comments of [docker-compose-example.yml](https://github.com/qwc-services/qwc-docker/blob/master/docker-compose-example.yml).
